### ISSUE TITLE
CTPT Series turns to ### instead of configured in the Dictionary

### ISSUE THREAD

**Issue by lordmight** [sonikf/ctpt#10]
Version Dolibarr: 18.0.3

OS: GNU/Linux

Web Server: Apache/2.4.54

PHP: 7.4.3-4

MariaDB/MySQL: 10.3.39

Screenshot
When Validating the Invoice
![image](https://github.com/sonikf/ctpt/assets/11439366/20d9bc32-6e68-43c4-a077-c190ba29ec2f)

Dictionary
![image](https://github.com/sonikf/ctpt/assets/11439366/82e5961e-7fd5-4bd1-8cfe-901c59a91e08)

Mercure
![image](https://github.com/sonikf/ctpt/assets/11439366/66448109-02fb-4fb3-a29e-91eb5b13eb33)

**Comment by sonikf** [comment]
Hi @lordmight,
I can't reproduce the error with same setup us yours!
Please read https://github.com/sonikf/ctpt/wiki/Support#troubleshooting and also try upgrading to Dolibarr 18.05

**Comment by KreativeKrise** [comment]
I have the same problem. It's only working if I set the `Third-party type` of a third-party. 
It doesn't matter what I choose for the new "Series" field. This seams to be completely ignored.

Tested with Dolibarr 19.0.3 and CTPT 1.0.5

**Comment by sonikf** [comment]
Ηι @KreativeKrise 
Please post screenshots of your set up both from dictionary and numbering model.

**Comment by KreativeKrise** [comment]
My dictionary setup:
![Dictionary_setup_-_Google_Chrome_2024-10-22_08-42-56](https://github.com/user-attachments/assets/5914acd1-2319-4592-8537-72766dd3c43b)

My numbering model setup:
![Invoices_module_setup_-_Google_Chrome_2024-10-22_08-42-28](https://github.com/user-attachments/assets/74a944a2-3e0b-4620-a140-bea203bd5e4b)

The result when I want to validate the invoice:
![(PROV4)_-_Card_-_Google_Chrome_2024-10-22_08-45-32](https://github.com/user-attachments/assets/0a053457-fbc0-4623-83ff-522309dd996b)

**Comment by sonikf** [comment]
Your setup looks good
Please check all file and folder permissions inside custom/ctpt folder
https://github.com/sonikf/ctpt/wiki/Support#troubleshooting

**Comment by KreativeKrise** [comment]
My Dolibarr permissions:
![2024-10-22_09-21-01](https://github.com/user-attachments/assets/5db45d58-95a3-4d34-9298-05cf78b66328)

File permissions:
![wsl@LT-822F9633_~dolibarrhtdocscustomctpt_2024-10-22_09-26-46](https://github.com/user-attachments/assets/0f9eaaaf-9418-4dd4-8aef-13c34911d23a)
