### ISSUE TITLE
Class 'Product' not found

### ISSUE THREAD

**Issue by smailag1** [sonikf/ctpt#8]
Hi
i get this error if i click config Botton on the model ! 
Fatal error: Uncaught Error: Class 'Product' not found in C:\wamp64\www\dol16\core\class\html.formsetup.class.php on line 1106
-----

Conf:
Wamp on Windows
dolibarr v 16
php 7.4.26
MySQL 5.7.36 
thank you

**Comment by sonikf** [comment]
Hi, this error is irrelevant to this module try dolibarr forums
https://www.dolibarr.org/forum/

Please post a screenshot after you hit validate button

Please see the wiki regarding the module, it's only in Greek at the moment

https://github.com/sonikf/ctpt/wiki/Setup

Troubleshooting:
https://github.com/sonikf/ctpt/wiki/Support#%CE%95%CF%80%CE%AF%CE%BB%CF%85%CF%83%CE%B7-%CF%80%CF%81%CE%BF%CE%B2%CE%BB%CE%B7%CE%BC%CE%AC%CF%84%CF%89%CE%BD

Troubleshooting tips in English

   - Make sure your user has the necessary permissions (user tab).


   - Make sure the htdocs/custom/ctpt folder and subfolders have the
   necessary permissions rwx r-x r-x or 755 and files rw- r-- r-- or 644 h2


   - Make sure (TE_) in the Third Party Types dictionary is in Latin.

Until Dolibarr version 16 the 3rd party Types dictionary does not support
non latin characters, but you can achieve this with a small change in
htdocs/core/lib/functions2.lib.php
from
$masktype_value = substr(preg_replace('/^TE_/', '', $objsoc->typent_code),
0, dol_strlen($regType[1]));
to
$masktype_value = dol_substr(preg_replace('/^TE_/', '',
$objsoc->typent_code), 0, dol_strlen($regType[1]));


   - The number of t's in the mercure mask must be the same as the number
   of characters after TE_ in the 3rd party Types dictionary.

e.g  {ttt}{0000} ->  TE_ABC


   - Finally, delete the extrafield from
   Settings->Modules-Invoices-Additional features (invoices) and
   disable/enable the module again


Στις Δευ 9 Ιαν 2023 στις 1:36 π.μ., ο/η smailag1 ***@***.***>
έγραψε:

**Comment by smailag1** [comment]
thanks
