### ISSUE TITLE
local Dolibarr 16.0.1

### ISSUE THREAD

**Issue by Xenoss0** [sonikf/ctpt#9]
Fatal error: Uncaught Error: Class 'Product' not found in C:\dolibarr\www\dolibarr\htdocs\core\class\html.formsetup.class.php:1106 Stack trace: #0 C:\dolibarr\www\dolibarr\htdocs\core\class\html.formsetup.class.php(323): FormSetupItem->generateOutputField() #1 C:\dolibarr\www\dolibarr\htdocs\core\class\html.formsetup.class.php(230): FormSetup->generateLineOutput(Object(FormSetupItem), false) #2 C:\dolibarr\www\dolibarr\htdocs\core\class\html.formsetup.class.php(165): FormSetup->generateTableOutput(false) #3 C:\dolibarr\www\dolibarr\htdocs\custom\ctpt\admin\setup.php(307): FormSetup->generateOutput() #4 {main} thrown in C:\dolibarr\www\dolibarr\htdocs\core\class\html.formsetup.class.php on line 1106

**Comment by sonikf** [comment]
Hi, please write the following 
Web Server:
PHP:
MariaDB/MySQL: 
and when this error occurs

There will be a new version in a few days to eliminate the error regarding CTPT

**Comment by ndrosis** [comment]
Hi @Xenoss0 check out the issue #8
